version: "3.9"

services:
  # -------------------
  # Zookeeper
  # -------------------
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_PORT_NUMBER: 2181
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/bitnami/zookeeper
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - packet_net

  # -------------------
  # Kafka Broker 1
  # -------------------
  kafka1:
    image: bitnami/kafka:3.5.1
    container_name: kafka1
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - kafka1-data:/bitnami/kafka
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions.sh", "--bootstrap-server", "kafka1:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - packet_net

  # -------------------
  # Kafka Broker 2
  # -------------------
  kafka2:
    image: bitnami/kafka:3.5.1
    container_name: kafka2
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - kafka2-data:/bitnami/kafka
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions.sh", "--bootstrap-server", "kafka2:9093"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - packet_net

  # -------------------
  # Kafka Broker 3
  # -------------------
  kafka3:
    image: bitnami/kafka:3.5.1
    container_name: kafka3
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - kafka3-data:/bitnami/kafka
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions.sh", "--bootstrap-server", "kafka3:9094"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - packet_net

  # -------------------
  # PostgreSQL
  # -------------------
  postgres:
    image: postgres:15-alpine
    container_name: postgresdb
    environment:
      POSTGRES_DB: packetdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tiger
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - packet_net
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d packetdb -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # -------------------
  # Packet Capture Producer Service
  # -------------------
  packetcaptureproducerservice:
    container_name: packetcaptureproducerservice
    image: ${ECR_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/packetcaptureproducerservice:${IMAGE_TAG}
    ports:
      - "8781:8781"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8781
      KAFKA_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9093,kafka3:9094
      KAFKA_TOPIC: packets1
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    networks:
      - packet_net
    restart: always

  # -------------------
  # Packet Capture Consumer Service
  # -------------------
  packetcaptureconsumerservice:
    container_name: packetcaptureconsumerservice
    image: ${ECR_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/packetcaptureconsumerservice:${IMAGE_TAG}
    ports:
      - "8782:8782"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/packetdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tiger
      SERVER_PORT: 8782
      KAFKA_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9093,kafka3:9094
      KAFKA_CONSUMER_GROUP: packet-consumer-group
    depends_on:
      postgres:
        condition: service_healthy
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    networks:
      - packet_net
    restart: always

  # -------------------
  # Packet Analyzer Service
  # -------------------
  packetanalyserservice:
    container_name: packetanalyserservice
    image: ${ECR_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/packetanalyserservice:${IMAGE_TAG}
    ports:
      - "8783:8783"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/packetdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tiger
      SERVER_PORT: 8783
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - packet_net
    restart: always

  # -------------------
  # Network Packet Capture Service
  # -------------------
  networkpacketcaptureservice:
    container_name: networkpacketcaptureservice
    image: ${ECR_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/networkpacketcaptureservice:${IMAGE_TAG}
    cap_add:
      - NET_RAW
      - NET_ADMIN
    ports:
      - "8785:8785"
    environment:
      PRODUCER_URL: http://packetcaptureproducerservice:8781/produce
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - packet_net
    restart: always

  # -------------------
  # Frontend
  # -------------------
  frontend:
    container_name: frontend
    image: ${ECR_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/frontend:${IMAGE_TAG}
    ports:
      - "3000:80"
    depends_on:
      - packetcaptureconsumerservice
      - packetcaptureproducerservice
      - packetanalyserservice
      - networkpacketcaptureservice
    networks:
      - packet_net
    restart: always

# -------------------
# Volumes
# -------------------
volumes:
  pgdata:
  kafka1-data:
  kafka2-data:
  kafka3-data:
  zookeeper-data:

# -------------------
# Networks
# -------------------
networks:
  packet_net:
    external: true
